"""Write the sidecar files that ship next to each rendered video.

Three artefacts come out of a render besides the MP4 itself: a caption file to
paste, a provenance record naming every source file that contributed a frame,
and a human-readable posting plan. The provenance record is the important one.
It is what lets the user answer "where did this footage come from" for any
frame of any post, months later, without guessing.
"""

from __future__ import annotations

import platform
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Sequence

from . import __version__
from .captions import PostCopy
from .curate import SelectionReport
from .presets import Preset
from .storyboard import Storyboard
from .util import human_duration, write_json

#: What each source label means, so the provenance file explains itself.
SOURCE_NOTES = {
    "envato": "Envato Elements or Market download. Covered by your Envato licence.",
    "artgrid": "Artgrid download. Covered by your Artgrid subscription.",
    "storyblocks": "Storyblocks download. Covered by your Storyblocks licence.",
    "adobe-stock": "Adobe Stock download. Covered by your Adobe Stock licence.",
    "shutterstock": "Shutterstock download. Covered by your Shutterstock licence.",
    "unsplash": "Unsplash download. Unsplash licence.",
    "pexels": "Pexels download. Pexels licence.",
    "camera": "Shot on your own camera or phone.",
    "photos-library": "Exported from your Photos library.",
    "local": "A file already on this machine. Confirm you hold the rights.",
}


@dataclass
class PostBundle:
    """Everything produced for one post."""

    slug: str
    preset: Preset
    board: Storyboard
    copy: PostCopy
    output: Path
    selection_report: SelectionReport | None = None
    music: Path | None = None
    rendered_at: float = field(default_factory=time.time)

    @property
    def directory(self) -> Path:
        """Folder the video and its sidecars live in."""
        return self.output.parent


def provenance(bundle: PostBundle) -> dict:
    """A record of every source file that contributed a frame to this post.

    Deliberately explicit that no generative model was involved. This project
    never calls one, so the claim is a statement of how the file was built
    rather than a guess about it.
    """
    seen: dict[str, dict] = {}
    for shot in bundle.board.shots:
        asset = shot.asset
        entry = seen.setdefault(
            asset.path,
            {
                "path": asset.path,
                "file": asset.name,
                "kind": asset.kind,
                "source": asset.source,
                "source_note": SOURCE_NOTES.get(asset.source, "Unclassified source."),
                "resolution": f"{asset.width}x{asset.height}",
                "licence_reference": "",
                "used_at": [],
            },
        )
        entry["used_at"].append(
            {"start": round(shot.start, 3), "length": round(shot.visible, 3)}
        )

    return {
        "post": bundle.slug,
        "generated_by": f"mbtok {__version__}",
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime(bundle.rendered_at)),
        "machine": platform.node(),
        "synthetic_media": False,
        "generative_ai_used": False,
        "pipeline_note": (
            "Every frame originates in one of the source files listed below. "
            "mbtok only scales, crops, moves, grades and cross-fades them. No "
            "image, video, voice or music was generated by a model at any point."
        ),
        "music": str(bundle.music) if bundle.music else None,
        "sources": sorted(seen.values(), key=lambda entry: entry["path"]),
    }


def sidecar(bundle: PostBundle) -> dict:
    """The complete machine-readable record of one post."""
    return {
        "slug": bundle.slug,
        "preset": {
            "key": bundle.preset.key,
            "title": bundle.preset.title,
            "blurb": bundle.preset.blurb,
        },
        "output": str(bundle.output),
        "copy": bundle.copy.to_dict(),
        "storyboard": bundle.board.to_dict(),
        "selection": (
            {
                "considered": bundle.selection_report.considered,
                "eligible": bundle.selection_report.eligible,
                "chosen": bundle.selection_report.chosen,
                "mean_score": round(bundle.selection_report.mean_score, 4),
                "warnings": bundle.selection_report.warnings,
            }
            if bundle.selection_report
            else None
        ),
        "provenance": provenance(bundle),
    }


def caption_text(bundle: PostBundle) -> str:
    """The caption file, ready to paste into the TikTok composer."""
    copy = bundle.copy
    lines = [
        copy.full_caption,
        "",
        "---",
        f"On-screen hook: {copy.hook}",
        f"Suggested posting window: {copy.posting_window}",
        f"Music brief: {bundle.preset.music}",
    ]
    return "\n".join(lines) + "\n"


def posting_plan(bundles: Sequence[PostBundle], title: str = "Posting plan") -> str:
    """A markdown plan covering one or many posts."""
    if not bundles:
        return f"# {title}\n\nNothing was rendered.\n"

    lines = [f"# {title}", ""]
    lines.append(f"{len(bundles)} post{'s' if len(bundles) != 1 else ''} ready to upload.")
    lines.append("")
    lines.append("| # | File | Mood | Length | Shots | Hook |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for index, bundle in enumerate(bundles, start=1):
        lines.append(
            f"| {index} | `{bundle.output.name}` | {bundle.preset.title} | "
            f"{human_duration(bundle.board.duration)} | {len(bundle.board.shots)} | "
            f"{bundle.copy.hook} |"
        )
    lines.append("")

    for index, bundle in enumerate(bundles, start=1):
        lines.extend(_plan_section(index, bundle))

    lines.extend(
        [
            "## Before you upload",
            "",
            "- Add the music inside TikTok if you want a trending sound. The rendered",
            "  audio is a guide track, and swapping to an in-app sound is usually worth",
            "  more reach than the mix you exported with.",
            "- Leave the top 15% and bottom 20% of the frame clear when you add captions",
            "  in the app. The rendered text already sits inside that safe area.",
            "- Post one video at a time. Two uploads in the same hour split their own",
            "  audience.",
            "- There is nothing to disclose under TikTok's synthetic-media policy: no",
            "  frame of these videos was generated by a model. See the provenance JSON",
            "  next to each file for the full source list.",
            "",
        ]
    )
    return "\n".join(lines)


def _plan_section(index: int, bundle: PostBundle) -> list[str]:
    """The per-post block of the posting plan."""
    copy = bundle.copy
    board = bundle.board
    grid = board.grid
    sources = sorted({shot.asset.source for shot in board.shots})
    videos = sum(1 for shot in board.shots if shot.is_video)

    lines = [
        f"## {index}. {bundle.preset.title} - `{bundle.output.name}`",
        "",
        f"**Hook on screen:** {copy.hook}",
        "",
        "**Caption to paste:**",
        "",
        "```",
        copy.full_caption,
        "```",
        "",
        f"- Length: {human_duration(board.duration)} across {len(board.shots)} shots "
        f"({videos} moving, {len(board.shots) - videos} stills)",
        f"- Posting window: {copy.posting_window}",
        f"- Music brief: {bundle.preset.music}",
    ]
    if grid:
        lines.append(
            f"- Cut to {grid.bpm:.0f} BPM ({grid.source}), every cut on the beat"
        )
    lines.append(f"- Footage sources: {', '.join(sources)}")
    if board.warnings:
        lines.append("- Warnings:")
        lines.extend(f"  - {warning}" for warning in board.warnings)
    lines.append("")
    return lines


def write_bundle(bundle: PostBundle) -> dict[str, Path]:
    """Write every sidecar for one post and return the paths written."""
    directory = bundle.directory
    directory.mkdir(parents=True, exist_ok=True)
    stem = bundle.output.stem

    caption_path = directory / f"{stem}.caption.txt"
    caption_path.write_text(caption_text(bundle), encoding="utf-8")

    sidecar_path = directory / f"{stem}.json"
    write_json(sidecar_path, sidecar(bundle))

    provenance_path = directory / f"{stem}.provenance.json"
    write_json(provenance_path, provenance(bundle))

    return {
        "caption": caption_path,
        "sidecar": sidecar_path,
        "provenance": provenance_path,
    }


def write_plan(bundles: Sequence[PostBundle], path: Path, title: str = "Posting plan") -> Path:
    """Write the markdown posting plan for a batch."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(posting_plan(bundles, title=title), encoding="utf-8")
    return path
